name: Aurora Android Release Workflow
on:
  push:
    tags:
      - v*

defaults:
  run:
    shell: bash

jobs:
  build-sign-generate-artifacts:
    name: Build & Sign Bundles, Generate Artifacts & Upload
    runs-on: ubuntu-latest
    steps:
    - name: Get Tag Name
      uses: olegtarasov/get-tag@v2
      id: tagName
      with:
        tagRegex: "v(.*)"
        tagRegexGroup: 1
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install NDK
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.1.5948944" --sdk_root=${ANDROID_SDK_ROOT}
    - name: Create .properties Files # create local.properties, secret.properties and sentry.properties
      env:
        SENTRY_PROPERTIES: ${{ secrets.SENTRY_PROPERTIES }}
        SECRET_PROPERTIES: ${{ secrets.SECRET_PROPERTIES }}
      run: |
        rm -f local.properties
        rm -f sentry.properties
        rm -f secret.properties
        touch local.properties
        echo 'sdk.dir=/usr/local/lib/android/sdk' >> local.properties
        echo 'ndk.dir=/usr/local/lib/android/sdk/ndk/20.1.5948944' >> local.properties
        touch sentry.properties
        echo "$SENTRY_PROPERTIES" >> sentry.properties
        touch secret.properties
        echo "$SECRET_PROPERTIES" >> secret.properties
        echo ".properties files created."
    - name: Build APKs and AAB
      run: |
        ./gradlew assemblePrivacyRelease 
        ./gradlew assembleRegularRelease
        ./gradlew bundleRegularRelease
    - name: Sign Privacy APK
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/privacy/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
    - name: Sign Regular APK
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/apk/regular/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
    - name: Sign Regular AAB
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/build/outputs/bundle/regularRelease/
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
    - name: Rename Bundles
      run: |
        mv app/build/outputs/apk/privacy/release/app-privacy-release-unsigned.apk app/build/outputs/apk/privacy/release/Tari-Aurora-$GIT_TAG_NAME-Private.apk
        mv app/build/outputs/apk/regular/release/app-regular-release-unsigned.apk app/build/outputs/apk/regular/release/Tari-Aurora-$GIT_TAG_NAME-Regular.apk
        mv app/build/outputs/bundle/regularRelease/app-regular-release.aab app/build/outputs/bundle/regularRelease/Tari-Aurora-$GIT_TAG_NAME-Regular.aab
    - name: Create Changelog
      id: changelog
      uses: metcalfc/changelog-generator@v0.4.1
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: v${{ steps.tagName.outputs.tag }}
        body: ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: false
    - name: Upload Privacy APK to the GitHub Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app/build/outputs/apk/privacy/release/Tari-Aurora-${{ steps.tagName.outputs.tag }}-Private.apk
        asset_name: Tari-Aurora-${{ steps.tagName.outputs.tag }}-Private.apk
        asset_content_type: application/vnd.android.package-archive
    - name: Upload Regular APK to the GitHub Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app/build/outputs/apk/regular/release/Tari-Aurora-${{ steps.tagName.outputs.tag }}-Regular.apk
        asset_name: Tari-Aurora-${{ steps.tagName.outputs.tag }}-Regular.apk
        asset_content_type: application/vnd.android.package-archive
    - name: Upload Regular AAB to Play Console
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: com.tari.android.wallet
        releaseFile: app/build/outputs/bundle/regularRelease/Tari-Aurora-${{ steps.tagName.outputs.tag }}-Regular.aab
        track: beta
        whatsNewDirectory: distribution/
    - name: Upload APKs to Browserstack
      env:
        BROWSERSTACK_SECRET: ${{ secrets.BROWSERSTACK_SECRET }}
      run: |
        curl -u "$BROWSERSTACK_SECRET" -X POST "https://api-cloud.browserstack.com/app-live/upload" -F "file=@app/build/outputs/apk/regular/release/Tari-Aurora-$GIT_TAG_NAME-Regular.apk"
        curl -u "$BROWSERSTACK_SECRET" -X POST "https://api-cloud.browserstack.com/app-live/upload" -F "file=@app/build/outputs/apk/privacy/release/Tari-Aurora-$GIT_TAG_NAME-Private.apk"
